### ISSUE TITLE
Crash on Startup- java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by AnonymousPuppy** [WayofTime/BloodMagic#125]
Using forge .1231, a custom modpack, and blood magic v1.2.0a. Also have bloodutils 1.3.1_B0(addon) and sanguimancy 1.1.7-19(addon).

Getting this crash on startup: http://pastebin.com/Lmg44hbN

This was after updating blood magic to v1.2.0a, from v1.2.0. Reverting back to v1.2.0 "fixes" this issue for the time being. Please take a look at this whenever you can, thank you.
